const base = 'http://localhost:5000'
export const loginURL = base + '/auth/login'
export const logoutURL = base + '/auth/logout'
export const registerURL = base + '/auth/register'
export const mensTopsURL = base + '/Mens/Tops'